version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dockers
      - POSTGRES_PASSWORD=dockers
      - POSTGRES_DB=nextjsdocker
    networks:
      - primeira-s
  nextjs-docker:
    restart: always
    container_name: nextjs-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://dockers:dockers@postgres:5432/nextjsdocker?schema=public
      - CUSTOMERS_HOST=postgres
      - CUSTOMERS_PORT=5432
    depends_on:
      - postgres
    networks:
      - primeira-s

networks:
  primeira-s:
    driver: bridge

volumes:
  db:
