version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    networks:
      - docker-devOps
  nextjs-docker:
    restart: always
    container_name: nextjs-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://dockers:dockers@postgres:5432/nextjsdocker?schema=public
      - CUSTOMERS_HOST=postgres
      - CUSTOMERS_PORT=5432
    depends_on:
      - postgres
    networks:
      - docker-devOps

networks:
  docker-devOps:
    driver: bridge

volumes:
  db:
